e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("products.urls"), name='home'),
    path('orders/', include("orders.urls"), name='home'),

]

orders/urls.py
from django.urls import path

from orders.views import OrderListView
from .views import create_order

app_name = 'orders'

urlpatterns = [
    path('create-order/<slug:slug>/', create_order, name='create_order'),
    path('orders/', OrderListView.as_view(), name='order_list'),
]

products/models.py
from django.db import models
from django.template.defaultfilters import slugify

from django.contrib.auth.models import User


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)
    sub_category = models.ForeignKey(
        'self', on_delete=models.CASCADE,
        related_name='sub_categories', null=True, blank=True
    )
    is_sub_category = models.BooleanField(default=False)
    description = models.TextField()

    def __str__(self):
        return f'Category ID: {self.id} - {self.name}'


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.PositiveIntegerField()
    product_image = models.ImageField(upload_to='static/images/products/')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=100, unique=True, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Product ID: {self.id} - {self.slug}'
    
    def save(self, *args, **kwargs):  # new
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)


class ProductReview(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} is reviewing {self.review}"

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Texno Shop</title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
        </li>
      
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
             data-bs-toggle="dropdown" aria-expanded="false">
              Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for category in categories %}
                  <li><a class="dropdown-item"
                         href="{% url 'index' %}?category={{ category.id }}">{{ category.name }}</a>
                  </li>
              {% endfor %}
         </ul>   
        </li>  

      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ search_query }}">
        <button class="btn btn-outline-success" type="submit">Search</button>
        {% if user.is_authenticated %}
        {% if user.is_staff %}
        <form class="d-flex">
                <a class="btn btn-warning ms-2" href="{% url 'orders:order_list' %}">Buyurtmalar</a>
        </form>
        {% else %}
          <form class="d-flex ms-2">
                <a class="btn btn-warning ms-2" href="{% url 'orders:order_list' %}">Mening buyurtmalarim</a>
          </form>
        {% endif %}
      {% endif %}

      {% if request.user.is_authenticated %}
    <form class="d-flex" role="search">
      <a href="{% url 'logout' %}" class="btn btn-warning ms-2">Log out</a>
    </form>
    {% else %}
    <form class="d-flex" role="search">
        <a href="{% url 'register' %}" class="btn btn-primary ms-2">Register</a>
        <a href="{% url 'login' %}" class="btn btn-success ms-2">Login</a>
    </form>
    {% endif %}

    {% if user.is_staff %}
      <form class="d-flex ms-2" role="search">
        <a  href="{% url 'create-post' %}" class="btn btn-danger ">Create post</a>
    </form>
      {% endif %}
    </div>
  </div>
</nav>
  {% block content %}
  
  {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

templates/create.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h2>Create Post</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

templates/create_order.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-6">
                <h3>{{ product.name }}</h3>
                <form method="post" class="form-conterol">
                    {% csrf_token %}
                    <label for="quantity">Mahsulot soni:</label>
                    <input type="number" id="quantity" name="quantity">
                    <label for="address">Mahsulot yetkazib berilishi kerak bo'lgan adres:</label>
                    <input type="text" id="address" name="address">
                    
                    <button class="btn btn-primary">Buyurtmani tasdiqlash</button>
                </form>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

templates/create_user.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="POST">

    {% csrf_token %}

    {{ create_form }}

    <button type="submit">Sign Up</button>
        
    </form>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}

{% block title %}Detail page{% endblock %}

{% block content %}

    <div class="container">
        <div class="col-md-12 py-5">
            <h1>{{ product.name }}</h1>
            <div class="row py-5">
                <div class="col-md-4 card">
                    <img src="{{ product.product_image.url }}" alt="{{ product.name }}">
                </div>
                <div class="col-md-4 card">
                    <h5>{{ product.description }}</h5>
                </div>
                <div class="col-md-4 card">
                    <h3>{{ product.price }}</h3>
                    <p>Standart yetkazib berish
                        Manzilga qarab 4 soatdan 3 kungacha yetkazib beriladi</p>
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'orders:create_order' product.slug %}" class="btn btn-success">Buyurtma
                        berish</a>
                {% else %}
                    <h3>Buyurtma berish uchun ro'yxatdan o'ting</h3>
                    <a href="{% url 'register' %}" class="btn btn-primary">Register</a>
                {% endif %}
                </div>
            </div>
            <div class="row">
                {% if request.user.is_authenticated %}
                    <div class="col-md-6">
                        <form class="form-control" action="" method="post">
                            {% csrf_token %}
                            <textarea name="review" id="review" cols="52" rows="3"></textarea>
                            <br>
                            <button class="btn btn-primary" type="submit">Send Review</button>
                        </form>
                    </div>
                {% else %}
                    <div class="col-md-4">
                        <p>Siz review qoldirish uchun ro'yxatdan o'tgan bo'lishingiz kerak</p>
                        <a href="{% url 'users:login' %}" class="btn btn-success">Login</a>
                    </div>
                {% endif %}
            </div>
            <div class="row">
                <div class="col-md-6">
                    <ul class="list-group list-group-flush">
                        {% for review in product_reviews %}
                            <li class="list-group-item">
                                <h5>{{ review.user.username }} | {{ review.created_at }}</h5>
                                <p>{{ review.review }}</p>
                                <li>
                                    <a href="{% url 'edit_comment' product.slug review.id %}">✏️</a>
                                    <a href="{% url 'delete-comment' product.slug review.id %}">❌</a>
                                </li>
                            </li>
                        {% endfor %}
                    </ul>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/edit_comment.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="col-md-12 p-5">
            <form method="POST" class="form-control">
                {% csrf_token %}

                {{ form }}
                <button class=" mx-5 btn btn-primary" type="submit">Save</button>
            </form>
        </div>
    </div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}

<h1>E commerce website</h1>

<div class="continer">
        <div class=" d-flex col-md-12 p-5">
            {% for product in product_list %}
                <div class="card ms-3" style="width: 18rem;">
                    <img src="{{ product.product_image.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <a href="{% url 'detail' product.slug %}">
                            <h5 class="card-title text-dark fw-italic">{{ product.name | truncatechars:20  }}</h5>
                        </a>
                        <p class="card-text">{{ product.description | truncatechars:30 }}</p>
                        <a href="#" class="btn btn-primary">Buy</a>
                        <span class="ms-5 fw-bolder">${{ product.price }}</span>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}


{% block content %}
    <form action="" method="POST">

    {% csrf_token %}

    {{ form }}
    <button type="submit" class="btn-warning">Log in</button>

    </form>
{% endblock %}

templates/order_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h2>Buyurtmalar ro'yxati</h2>
    <ul class="list-group">
        {% for order in orders %}
            <li class="list-group-item">
                Buyurtma ID: {{ order.id }} - User: {{ order.user.username }} - Name: {{ order.product.name }} - Date: {{ order.order_date}}
                <ul>
                    {% for item in order.items.all %}
                        <li>{{ item.product.name }} - {{ item.quantity }} pcs - {{ item.address }}</li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}